[build-options]
  observabilityIncluded = true

[package]
  distribution = "2201.1.2"
  export = ["ecommerceapp"]
  icon = "docs/icon.png"
  keywords = ["Type/GraphQL","Category/Service","Internal/http"]
  name = "ecommerceapp"
  org = "amilaja"
  version = "1.0.1"

[[platform.java11.dependency]]
groupId = "mysql"
artifactId = "mysql-connector-java"
version = "8.0.20"